/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bariacg (https://sketchfab.com/bariacg)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cactus-963b6301f7fb4bff90d2920b53a98fc5
Title: Cactus
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import model from "./cactus_min.glb"

export function CactusModel(props) {
  const { nodes, materials } = useGLTF(model);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Sphere002_Material_#25_0"].geometry}
          material={materials.Material_25}
          position={[0,0,0]}
          scale={1}
        >
          {props.wireframe && props.wireframe === true ?
          <meshBasicMaterial attach="material" color={props.color ? props.color : 'red'} wireframe fog={false}/>
          : undefined}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/cactus_min.glb");