/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bluekiwi.dog (https://sketchfab.com/bluekiwi.dog)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hare-animated-948938cd237d49a9868662213fa05543
Title: Hare (animated)
*/

import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as SkeletonUtils from 'three/addons/utils/SkeletonUtils.js';
import model from "./hare_min.glb"
import { useGraph } from "@react-three/fiber";
import { animated, useSpring } from "@react-spring/three";

export function HareModel(props) {
  const group = useRef();
  const { materials, animations, scene } = useGLTF(model);
  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[props.animation]].play().startAt(Math.floor(Math.random() * 5));
  }, [actions,names]);
  return (
    <group ref={group} {...props}  dispose={null}>
      <animated.group rotation-y={props.rotationY ? props.rotationY : 0} name="Sketchfab_Scene" position={[2,0,0]}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="6b6db248e2724aeca73e8cf71e3bb6d4fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Light"
                  position={[407.625, 590.386, -100.545]}
                  rotation={[1.89, 0.881, -2.045]}
                  scale={100}
                >
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group
                  name="Rabbit"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Armature"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name="Object_9">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_12"
                      geometry={nodes.Object_12.geometry}
                      material={materials.puple}
                      skeleton={nodes.Object_12.skeleton}
                    />
                    <skinnedMesh
                      name="Object_13"
                      geometry={nodes.Object_13.geometry}
                      material={materials.emission}
                      skeleton={nodes.Object_13.skeleton}
                    >
                      {props.wireframe && props.wireframe === true ?
                      <meshBasicMaterial attach="material" color="#0000ff" wireframe fog={false}/>
                      : undefined}
                    </skinnedMesh>
                    <group
                      name="Object_11"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </animated.group>
    </group>
  );
}

useGLTF.preload("/hare_min.glb");