/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import model from "./we2002model.glb"

export function WE2002Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(model);
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]].startAt(0).play();
  }, [actions,names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
          <skinnedMesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.TEX}
            skeleton={nodes.Cube.skeleton}
          />
          <skinnedMesh
            name="Cube001"
            geometry={nodes.Cube001.geometry}
            material={materials.TEX}
            skeleton={nodes.Cube001.skeleton}
          />
          <skinnedMesh
            name="Cube002"
            geometry={nodes.Cube002.geometry}
            material={materials.TEX}
            skeleton={nodes.Cube002.skeleton}
          />
          <group name="Cube003">
            <skinnedMesh
              name="Cube003_1"
              geometry={nodes.Cube003_1.geometry}
              material={materials.TEXTURA_PIEL}
              skeleton={nodes.Cube003_1.skeleton}
            />
            <skinnedMesh
              name="Cube003_2"
              geometry={nodes.Cube003_2.geometry}
              material={materials.TEX}
              skeleton={nodes.Cube003_2.skeleton}
            />
          </group>
          <group name="Cube004">
            <skinnedMesh
              name="Cube004_1"
              geometry={nodes.Cube004_1.geometry}
              material={materials.TEXTURA_PIEL}
              skeleton={nodes.Cube004_1.skeleton}
            />
            <skinnedMesh
              name="Cube004_2"
              geometry={nodes.Cube004_2.geometry}
              material={materials.TEX}
              skeleton={nodes.Cube004_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="Cube005"
            geometry={nodes.Cube005.geometry}
            material={materials.TEXTURA_PIEL}
            skeleton={nodes.Cube005.skeleton}
          />
          <skinnedMesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={materials.TEXTURA_PIEL}
            skeleton={nodes.Cube006.skeleton}
          />
          <skinnedMesh
            name="Cube007"
            geometry={nodes.Cube007.geometry}
            material={materials.TEXTURA_PIEL}
            skeleton={nodes.Cube007.skeleton}
          />
          <skinnedMesh
            name="Plane"
            geometry={nodes.Plane.geometry}
            material={materials.TEX}
            skeleton={nodes.Plane.skeleton}
          />
          <skinnedMesh
            name="Plane001"
            geometry={nodes.Plane001.geometry}
            material={materials.TEX}
            skeleton={nodes.Plane001.skeleton}
          />
          <skinnedMesh
            name="Plane002"
            geometry={nodes.Plane002.geometry}
            material={materials.TEXTURA_PIEL}
            skeleton={nodes.Plane002.skeleton}
          />
          <skinnedMesh
            name="Plane003"
            geometry={nodes.Plane003.geometry}
            material={materials.TEXTURA_PIEL}
            skeleton={nodes.Plane003.skeleton}
          />
          <skinnedMesh
            name="Plane004"
            geometry={nodes.Plane004.geometry}
            material={materials.TEXTURA_PIEL}
            skeleton={nodes.Plane004.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
        <group
          name="Camera"
          position={[0.133, 2.093, 7.048]}
          rotation={[1.522, 0.001, -0.003]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/we2002model.glb");